### ISSUE TITLE
Provide checkpoints

### ISSUE THREAD

**Issue by PW812** [adept-thu/RoboFusion#1]
Thank you so much for this great job!
I wonder if you provide this checkpoints?
https://github.com/adept-thu/RoboFusion/blob/01f9f46be906615d31e071261dff36850c2f3dd2/focalconvsamfusion/OpenPCDet/tools/cfgs/kitti_models/sam_onlinev3.yaml#L55

**Comment by modaxiansheng** [comment]
https://pan.baidu.com/s/1r7J50b-A9P4iuWfl6-FAaw?pwd=8888

**Comment by modaxiansheng** [comment]
https://github.com/facebookresearch/segment-anything?tab=readme-ov-file#model-checkpoints

**Comment by modaxiansheng** [comment]
../checkpoints/sam_image_encoder_b.pth==ViT-B SAM model(https://github.com/facebookresearch/segment-anything?tab=readme-ov-file#model-checkpoints)

**Comment by meyneryyangg** [comment]
but actually, when I use this checkpoint it turns out Error 
It seems like it is come from the difference between the weight and the model
Am I miss something?
I am sorry about asking this stupid problem
