### ISSUE TITLE
Where is the adaptive fusion in the transfusion?

### ISSUE THREAD

**Issue by Da1symeeting1** [adept-thu/RoboFusion#2]
Thanks for the amazing work you have done! I am new guy here , and i want to knnow after getting img-depth features and lidar features where is the fusion operation? looking forward to your reply.(sry for the stupid question)

**Comment by modaxiansheng** [comment]
Yes, TransFusion uses its own fusion solution.

**Comment by modaxiansheng** [comment]
![Uploading 3507feffcd154803668491d7ec2255e.png…]()

**Comment by modaxiansheng** [comment]
Please refer to Section 4.2 Experimental Settings in the paper for detailed information on 【RoboFusion with nuScenes and nuScenes-C】.

**Comment by modaxiansheng** [comment]
It is noteworthy that the Adaptive Fusion module is applied exclusively to Focals Conv rather than TransFusion, while TransFusion uses its own fusion module.

**Comment by Da1symeeting1** [comment]
thanks for the great work !

**Comment by Da1symeeting1** [comment]
Can you link the Adaptive Fusion module, that would be nice . THX again

**Comment by modaxiansheng** [comment]
https://github.com/adept-thu/RoboFusion/blob/ac0aa4a1817f1e81eabc9a3a8504e0de7f53beb9/focalconvsamfusion/OpenPCDet/pcdet/models/backbones_3d/focal_sparse_conv/focal_sparse_conv3_db.py#L112C48-L112C62

**Comment by Da1symeeting1** [comment]
very grateful for your hlep ! Thx again!
